version: 2.1

orbs:
  architect: giantswarm/architect@4.35.5

workflows:
  build:
    jobs:
      - architect/go-build:
          name: build
          binary: resource-police
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          name: "package and push resource-police"
          app_catalog: "giantswarm-operations-platform-catalog"
          app_catalog_test: "giantswarm-operations-platform-test-catalog"
          chart: "resource-police"
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/
