version: 2.1

orbs:
  architect: giantswarm/architect@4.34.1

workflows:
  build:
    jobs:
      - architect/go-build:
          name: build
          binary: resource-police
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-resource-police-to-quay
          image: "quay.io/giantswarm/resource-police"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          name: "package and push resource-police"
          app_catalog: "giantswarm-operations-platform-catalog"
          app_catalog_test: "giantswarm-operations-platform-test-catalog"
          chart: "resource-police"
          requires:
            - push-resource-police-to-quay
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
