apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.name }}
  metadata:
    labels:
      app: {{ .Values.name }}
      giantswarm.io/service-type: "managed"
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app: {{ .Values.name }}
        giantswarm.io/service-type: "managed"
    spec:
      template:
        metadata:
          labels:
            app: {{ .Values.name }}
            giantswarm.io/service-type: "managed"
        spec:
          containers:
          - args:
            - report
            - --installations.config.file=/resource-police-config/installations.yaml
            env:
            - name: SLACK_WEBHOOK_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: slackWebhookEndpoint
                  name: {{ .Values.name }}
            image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
            imagePullPolicy: Always
            name: {{ .Values.name }}
            volumeMounts:
            - mountPath: /resource-police-config
              name: {{ .Values.name }}
              readOnly: true
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumes:
          - name: {{ .Values.name }}
            secret:
              defaultMode: 420
              items:
              - key: installations.yaml
                path: installations.yaml
              secretName: {{ .Values.name }}
  schedule: "0 8,17 * * 1-5"
  successfulJobsHistoryLimit: 3
