{{- if .Values.global.podSecurityStandards.enforced }}
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
spec:
  exceptions: []
  match:
    any:
      - resources:
          kinds:
            - Pod
            - CronJob
            - Job
          namespaces:
            - {{ .Release.Namespace }}
          names:
            - karpenter*
{{- end }}
