apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    giantswarm.io/service-type: "managed"
type: Opaque
stringData:
  slackWebhookEndpoint: {{ .Values.slackWebhookEndpoint }}
  cortexPassword: {{ .Values.cortexPassword }}
