apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
type: Opaque
stringData:
  slackWebhookEndpoint: {{ .Values.slackWebhookEndpoint }}
  cortexPassword: {{ .Values.cortexPassword }}
