apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    giantswarm.io/service-type: "managed"
type: Opaque
stringData:
  slack-webhook-endpoint: {{ .Values.slackWebhookEndpoint }}
  installations.yaml: |-
{{ .Values.installations | toYaml | indent 4 }}
